# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='blog',
            new_name='post',
        ),
    ]
