# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20171112_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
