# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20171112_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
    ]
