# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20171119_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.AddField(
            model_name='image',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
