# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 02:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='test'),
            preserve_default=False,
        ),
    ]
