# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20180124_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
