# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 17:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20180125_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<insert content here>'),
        ),
    ]
